Repository DSM-Maradi/Maradi-frontend, pull requests merged in 2022-11, with the labels that each got.

#16 # 14 명예의 전당
  src/App.tsx
  src/assets/img/hall_background.png
  src/assets/img/index.ts
  src/assets/img/profile_image.png
  src/components/common/header/index.tsx
  src/components/common/header/nameList/index.tsx
  src/components/hall/index.tsx
  src/constance/hall/index.ts
  src/styles/theme.ts
Labels: documentation, 퍼블리싱

#17 FEAT : 프로젝트 읽기 퍼블리싱
  src/App.tsx
  src/assets/img/commentImg.svg
  src/assets/img/index.ts
  src/assets/img/like.svg
  src/assets/img/roundProfileImg.png
  src/assets/img/share.svg
  src/components/seeproject/index.tsx
Labels: 퍼블리싱

#19 Oauth
  package.json
  public/index.html
  src/App.tsx
  src/apis/auth/auth.ts
  src/components/common/header/index.tsx
  src/components/loginModal/index.tsx
  src/components/main/index.tsx
  src/constance/hall/index.ts
  src/index.tsx
  src/modules/.gitkeep
  src/modules/recoil/atom.ts
  yarn.lock
Labels: enhancement
